POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Evento para o teste",
  "details": null,
  "maximumAttendees": 1
}


###

POST http://localhost:3333/events/342f9680-a435-4211-99c9-bc031bee38fe/attendees
Content-Type: application/json

{
  "name": "Legionario",
  "email": "nunespflavio@gmail.com"
}

###

GET http://localhost:3333/events/342f9680-a435-4211-99c9-bc031bee38fe

###

GET http://localhost:3333/attendees/2/badge

###

GET http://localhost:3333/attendees/2/check-in

###

GET http://localhost:3333/events/03b4a1db-d40d-47d3-a12b-87471b62e561/attendees

###

GET http://localhost:3333/events/03b4a1db-d40d-47d3-a12b-87471b62e561/attendees?query=legionario
